version: '3.7'
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/application
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment: 
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      XDEBUG_CONFIG: remote_host=host.docker.internal
#    depends_on:
#      - db

  nginx:
    build:  
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes: 
      - .:/application
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on: 
      - php

#  db:
#    image: mysql:5.7
#    ports:
#      - "33086:3306"
#    environment:
#      MYSQL_DATABASE: ${DB_DATABASE}
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}